name: ChunkHoppers
version: 1.1
api-version: 1.13
author: Stellrow
main: ro.Stellrow.ChunkHoppers.ChunkHoppers

commands:
  ch:
    description: Main Chunk Hopper command
    usage: /ch give player amount
    aliases:
      - ChunkHopper